version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:full-1.5.5
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ./ubuntu1604-docker.json
  build-base:
    docker:
      - image: hashicorp/packer:full-1.5.5
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - attach_workspace:
          at: ~/packer
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build base
          command: packer build ./ubuntu1604-docker.json
          no_output_timeout: 30m
#      - persist_to_workspace:
#          root: .
#          paths:
#            - manifest-base.json
#      - store_artifacts:
#          path: manifest-base.json
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          requires:
            - validate